#!/bin/sh
PASS=$1
KEY=$2
IV=$3

if [ $# -ne 3 ]; then
	echo "USAGE: ./tripledes [text_to_encrypt] [keyfile.bg] [vectorfile.bg]"
	exit 1
fi

if [ ! -f $KEY ]; then
	echo "Error, file $KEY does not exist."
	exit 1
fi

if [ ! -f $IV ]; then
	echo "Error, file $IV does not exist."
	exit 1
fi


if type -p java; then
	    echo  Checking Java executable in PATH....OK
	        _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
	    echo Found java executable in JAVA_HOME ...OK    
		_java="$JAVA_HOME/bin/java"
else
       	echo "Java executable not found. Please install java >= 1.8 and try again.."
	exit
        fi
	
	if [[ "$_java" ]]; then
		version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
		echo Java version is"$version"
		if [[ "$version" > "1.8" ]]; then
			echo version is more than 1.8, OK
		else         
			echo version is less than 1.8 . Please upgrade to Java 1.8.x
			exit 1
		fi
	fi

java -Dpass=$1 -jar target/tripledescryptor-0.0.1-SNAPSHOT.jar --keyPath=$2 --ivPath=$3
